config/routes.rb
Inventoryxuno::Application.routes.draw do
  resources :concepts

  devise_for :users
  get "welcome/index"

  root 'welcome#index'

end

app/models/concept.rb
class Concept < ActiveRecord::Base

	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :concepts, :dependent => :destroy       
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :set_concept, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!


  # GET /concepts
  # GET /concepts.json
  def index

    @concepts = Concept.where(user: current_user)
  end

  # GET /concepts/1
  # GET /concepts/1.json
  def show
  end

  # GET /concepts/new
  def new
    @concept = Concept.new
  end

  # GET /concepts/1/edit
  def edit
  end

  # POST /concepts
  # POST /concepts.json
  def create
    @concept = Concept.new(concept_params)
    @concept.user= current_user

    respond_to do |format|
      if @concept.save
        format.html { redirect_to @concept, notice: 'Concept was successfully created.' }
        format.json { render action: 'show', status: :created, location: @concept }
      else
        format.html { render action: 'new' }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concepts/1
  # PATCH/PUT /concepts/1.json
  def update
    respond_to do |format|
      if @concept.update(concept_params)
        format.html { redirect_to @concept, notice: 'Concept was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1
  # DELETE /concepts/1.json
  def destroy
    @concept.destroy
    respond_to do |format|
      format.html { redirect_to concepts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concept
      @concept = Concept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concept_params
      params.require(:concept).permit(:cantidad, :nombre, :signo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/concepts/_form.html.erb
<%= form_for @concept, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :cantidad, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cantidad, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :signo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :signo, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                concepts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/concepts/edit.html.erb
<%- model_class = Concept -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/concepts/index.html.erb
<%- model_class = Concept -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:cantidad) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:signo) %></th>
      <th><%= model_class.human_attribute_name(:uuid) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= link_to concept.id, concept_path(concept) %></td>
        <td><%= concept.cantidad %></td>
        <td><%= concept.nombre %></td>
        <td><%= concept.signo %></td>
        <td><%= concept.uuid %></td>
        <td><%= concept.user_id %></td>
        <td><%=l concept.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_concept_path(concept), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      concept_path(concept),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_concept_path,
            :class => 'btn btn-primary' %>

app/views/concepts/new.html.erb
<%- model_class = Concept -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/concepts/show.html.erb
<%- model_class = Concept -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:cantidad) %>:</strong></dt>
  <dd><%= @concept.cantidad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @concept.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:signo) %>:</strong></dt>
  <dd><%= @concept.signo %></dd>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              concepts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_concept_path(@concept), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              concept_path(@concept),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <%= image_tag "uno.png", :size => "100x100", class: "img-rounded", id: "foto_derecha"%>
	      </a>

	      <p class="brand"> <%=link_to "Inventory X", root_url,  id: "logo"%> </p>

	      <div class="nav-collapse collapse navbar-responsive-collapse">
	        <ul class="nav">
	          <li class="divider-vertical"></li> 
	          <li>
	          	<%=link_to "Mi inventario", concepts_path,  id: "logo"%> </p>		
	          </li>
	          <li class="dropdown">
	            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Heramientas<b class="caret"></b></a>
	            <ul class="dropdown-menu">          

	            </ul>
	          </li>

	         

	      
	        </ul>
	        <!-- <form class="navbar-search pull-left" action="">
	          <input type="text" class="search-query span2" placeholder="Search">
	        </form> -->
	  		<ul class="nav pull-right">
	          <% if user_signed_in? %>
	            <li><%= link_to current_user.email, root_url %></li> 
	            <li><%= link_to "Desconectarse", destroy_user_session_path, :method => :delete %></li>
	          <% else %>
	            <li><%= link_to "Date de alta", new_user_registration_path %></li><li><%= link_to "Logeate", new_user_session_path %></li>
	          <% end %>        
	        </ul>
	      </div><!-- /navbar-colapse -->      
	    </div><!-- /navbar-inner --> 
	  </div><!-- /container -->   
	</header><!-- /navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Inventoryxuno" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
  <%= render 'layouts/header' %>

    <div class="container-fluid">
      <div class="row-fluid">

        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>